#!/usr/bin/env python3
from __future__ import annotations

import plistlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RECON = ROOT / "re" / "RECONSTRUCTION"

REQUIRED_SYNTHESIS = {
    "CarPlayCloak.m", "CarSleeper.m", "CNABConn.m", "Cpuigen.m",
    "CrashReporting.m", "DataRouter.m", "DDzCommit.m", "DDzCore.m",
    "DDzPicker.m", "EventLaunch.m", "Evict.m", "FastRelayout.m",
    "HostedCallbacks.m", "HostSplit.m", "HudBle.m", "KBObservers.m",
    "KeyboardHooks.m", "KeyinputRelay.m", "License.m", "LocaleFlow.m",
    "Migration.m", "PollFlush.m", "PrefsResolver.m", "PresentCommitAck.m",
    "Respring.m", "SiriProbe.m", "SpawnLaunch.m", "SpawnMisc.m",
    "SpawnTeardown.m", "SpikeHosting.m",
}

missing = sorted(name for name in REQUIRED_SYNTHESIS if not (RECON / name).is_file())
if missing:
    raise SystemExit(f"missing reconstruction synthesis files: {', '.join(missing)}")

for required in [
    ROOT / "Makefile",
    ROOT / "control",
    ROOT / "DuoDashReconstruction.plist",
    RECON / "DuoDashShared.h",
    RECON / "ReconstructionRuntime.h",
    RECON / "ReconstructionRuntime.m",
    RECON / "Tweak.x",
]:
    if not required.is_file():
        raise SystemExit(f"missing build input: {required.relative_to(ROOT)}")

makefile = (ROOT / "Makefile").read_text(encoding="utf-8")
for source in ["Tweak.x", "ReconstructionRuntime.m"]:
    if source not in makefile:
        raise SystemExit(f"Makefile does not include {source}")
if "DuoDashReconstruction_LIBRARIES = proc" not in makefile:
    raise SystemExit("Makefile must link libproc for the reconstructed 7764C liveness probe")

with (ROOT / "DuoDashReconstruction.plist").open("rb") as fh:
    filter_plist = plistlib.load(fh)

filter_dict = filter_plist.get("Filter", {})
expected_bundles = {
    "com.apple.springboard",
    "com.apple.Preferences",
    "com.apple.CarPlayApp",
    "com.apple.UIKit",
}
if set(filter_dict.get("Bundles", [])) != expected_bundles:
    raise SystemExit("Substrate bundle filter drifted from reconstructed artifact")
if set(filter_dict.get("Executables", [])) != {"mediaserverd", "kbd"}:
    raise SystemExit("Substrate executable filter drifted from reconstructed artifact")

runtime = (RECON / "ReconstructionRuntime.m").read_text(encoding="utf-8")
for contract in [
    "DDDetectRole",
    "DDBuildKnownAppBridgeSnapshot",
    "DDRepublishKnownAppBridgeSnapshot",
    "DDCachedStringValue",
    "DDCachedCarPlayUIMore",
    "DDCachedAutostartEnabled",
    "DDCachedFractionValue",
    "DDCachedFractionLayoutValue",
    "DDValidateIntegerValue(value, 0, 99, 0, NULL)",
    "DDValidateIntegerValue(value, 0, 8, 0, NULL)",
    "DDReadKeyPaneEnabled",
    "DDReadBridgedFontFloor",
    "DDValidateIntegerValue",
    "DDNormalizeIntegerSetting",
    "CFNumberIsFloatType",
    "DDIntegerValidationString",
    "DDIntegerValidationError",
    "DDSetAppBridgeLayout",
    "DDSetCarPlayUI",
    "DDToggleAppBridgeAutostart",
    "DDEvictCarPlayUIBundle",
    "DDCountLiveSnapshotEntries",
    "DDPostDistributedNotification",
    "DDObserveDistributedNotification",
    "DDPostUIAppRequest",
    "DDPostUIAppState",
    "DDPostUIAppFontFloorState",
    "DDPostUIAppKeyPaneState",
    "DDCurrentUIAppBridgeState",
    "DDReconstructionUIAppObserver",
    "DDConsumeUIAppStateUserInfo",
    "DDConsumeUIAppFontFloorUserInfo",
    "DDConsumeUIAppKeyPaneUserInfo",
    "DDTemporaryMarkerPath",
    "duodash_ab_nostatetimeout",
    "duodash_ab_bg_teardown",
    "UIApplicationDidBecomeActiveNotification",
    "UIApplicationDidEnterBackgroundNotification",
    "DDStartUIAppIPC",
    "DUODASH_AB_UIAPP_IPC_HOOKED",
    "DDHostSlotSize",
    "DDReadHostOrientation",
    "DDResolveSingleHostMirrorSize",
    "duodash_ab_rscale",
    "duodash_ab_canvas",
    "isEqualToString:@\"portrait\"",
    "scale < 1.0 || scale > 3.0",
    "DDParseLandscapeOverride",
    "DDResolveSplitHostOrientationFromAcceptedOverride",
    "DDResolveCoordinatedSplitHostOrientation",
    "DDPrepareSplitHostMirrorFromEnvironment",
    "duodash_ab_lscape.tripped",
    "duodash_ab_lscape.inflight",
    "respring_planned",
    "plannedStat.st_mtimespec.tv_sec >= inflightStat.st_mtimespec.tv_sec",
    "[@\"tripped\\n\" writeToFile:kDDLandscapeTrippedPath",
    "O_WRONLY | O_CREAT | O_TRUNC",
    "DDClearHostLandscapeOverrideState(YES)",
    "landscapeOverrideOrientation",
    "landscapeSwap",
    "landscapeCSwap",
    "landscapeRotationDegrees",
    "[token isEqualToString:@\"swap\"]",
    "[token isEqualToString:@\"cswap\"]",
    "[token hasPrefix:@\"rot=\"]",
    "fabs(value) > 360.0",
    "DDPrepareSingleHostMirror",
    "DDPrepareSplitHostMirror",
    "DDUpdateHostSlotMirror",
    "DDResetHostSlotMirror",
    "DDCurrentHostSlotMirror",
    "DDApplyLandscapeSwapToSize",
    "gDDHostLandscapeOverrideOrientation != 0 && gDDHostLandscapeSwap",
    "DDHostLandscapeGeometryPlan",
    "DDComputeHostLandscapeGeometryPlan",
    "MIN(slotWidth / nativeSize.width, slotHeight / nativeSize.height)",
    "gDDHostLandscapeCSwap ? nativeSize.height : nativeSize.width",
    "gDDHostLandscapeRotationDegrees * 3.14159265 / 180.0",
    "slotX + slotWidth * 0.5",
    "DDSceneGeometryUpdatesEnabled",
    "duodash_ab_noscenegeom",
    "gDDSceneGeometryEnabledCache",
    "DDSceneSettingsHasInterfaceOrientationIvar",
    "UIApplicationSceneSettings",
    "_interfaceOrientation",
    "DDAuxScenePreparation",
    "DDAuxSceneOrientationMutationSupported",
    "DDClassHasVoidIntegerSetter",
    "FBScene",
    "updateSettingsWithBlock:",
    "UIMutableApplicationSceneSettings",
    "setInterfaceOrientation:",
    "DDPrepareAuxSceneCandidate",
    "auxControllerAlreadyExists",
    "DDHostMirrorRejectsAuxBundle",
    "DDCommitAuxSceneMirrorAfterApplicationLookup",
    "applicationLookupSucceeded",
    "DDClearAuxSceneMirror",
    "DDCurrentAuxSceneMirror",
    "DDAuxSceneSettingsPlan",
    "DDCurrentAuxSceneSettingsPlan",
    "DDAuxSceneSettingsNeedUpdate",
    "gDDAuxSwapEnabled ? gDDAuxNativeSize.height : gDDAuxNativeSize.width",
    "fabs(currentFrameSize.width - plan.frameSize.width) <= 0.5",
    "currentOrientation == 0 || currentOrientation == plan.orientation",
    "DDAuxSceneSettingsAttempt",
    "kDDAuxCreateKickRetryDelays[] = { 0.1, 0.5, 1.5 }",
    "DDAuxCreateKickRetryDelays",
    "DDAuxCreateKickRetriesEnabled",
    "gDDAuxOrientation != 0 && !DDSceneSettingsHasInterfaceOrientationIvar()",
    "DDAuxCreateKickShouldRequestPrivateSceneObject",
    "capturedGeneration == gDDAuxGeneration && !gDDAuxSettingsApplied",
    "DDBeginAuxSceneSettingsAttempt",
    "gDDAuxSettingsAttemptCount >= 8",
    "gDDAuxSettingsBudget = 0",
    "gDDAuxSettingsBudget--",
    "gDDAuxSettingsAttemptCount++",
    "gDDAuxSettingsInFlight = YES",
    "DDBeginAuxSceneSettingsApply",
    "gDDAuxSettingsInFlight = NO",
    "gDDAuxSettingsExecutorReentrant = YES",
    "DDCompleteAuxSceneSettingsApply",
    "gDDAuxSettingsApplied = YES",
    "DDResolveAuxSettingsMutationExceptionOutcome",
    "DDAuxSettingsMutationExceptionSiteFramePath",
    "DDAuxSettingsMutationExceptionSiteOrientationPath",
    "outcome.shouldSkipRemainingMutation = YES",
    "outcome.frameAppliedWriteCouldHaveOccurredBeforeException = YES",
    "outcome.orientationAppliedWriteWouldBeSkipped = YES",
    "DDResolveAuxSettingsExecutorExceptionOutcome",
    "settingsAppliedWriteWouldBeSkipped",
    "outcome.shouldDecrementFailureCounter",
    "outcome.shouldClearReentrantState",
    "outcome.shouldDisposeByrefCaptures",
    "outcome.nonmatchingCatchTypeWouldResumeUnwind",
    "outcome.nonmatchingCatchTypeWouldClearReentrantState = NO",
    "outcome.nonmatchingCatchTypeWouldDecrementFailureCounter = NO",
    "outcome.nonmatchingCatchTypeWouldDisposeByrefCaptures = YES",
    "DDResolveAuxSettingsPreparationExceptionOutcome",
    "DDAuxSettingsPreparationExceptionSiteInitialAuxGate",
    "DDAuxSettingsPreparationExceptionSiteCurrentFrameRead",
    "DDAuxSettingsPreparationExceptionSiteCurrentOrientationRead",
    "DDAuxSettingsPreparationExceptionSiteLateUpdatePreparation",
    "outcome.shouldSkipRemainingPreparation = YES",
    "outcome.shouldContinueFinalOuterCleanup = YES",
    "outcome.retainedWorkingObjectReleaseWouldBeBypassed = YES",
    "DDSceneIdentityRoute",
    "DDSceneIdentityRouteHostSlot",
    "DDSceneIdentityRouteAux",
    "DDBundleIdentifierMatchesAux",
    "DDResolveSceneIdentityResolutionExceptionOutcome",
    "DDSceneIdentityResolutionExceptionOutcome outcome = { YES, YES, YES }",
    "DDResolveSceneResolverExceptionOutcome",
    "DDSceneResolverExceptionSitePrimarySceneIfExistsPath",
    "DDSceneResolverExceptionSiteFallbackScenePath",
    "outcome.exceptionWouldPropagate = YES",
    "outcome.shouldReturnNilScene = YES",
    "outcome.nonmatchingCatchTypeWouldResumeUnwind = YES",
    "DDResolveSceneDiagnosticSummaryExceptionOutcome",
    "DDSceneDiagnosticSummaryExceptionSiteSceneHandleResolution",
    "DDSceneDiagnosticSummaryExceptionSiteDiagnosticFormatting",
    "DDSceneDiagnosticSummaryFallbackThrew",
    "outcome.fallbackKind = DDSceneDiagnosticSummaryFallbackThrew",
    "outcome.guaranteedRetainedIntermediateReleaseBypassCount = 3",
    "outcome.additionalFormattedIntermediateReleaseCouldBeBypassed = YES",
    "DDResolveBundleNormalizationExceptionOutcome",
    "DDBundleNormalizationExceptionSiteApplicationControllerLookup",
    "DDBundleNormalizationExceptionSitePerItemApplicationLookup",
    "outcome.shouldForceApplicationControllerNil = YES",
    "outcome.shouldPreserveSanitizedCandidate = YES",
    "outcome.shouldAddCandidateAndContinueLoop = YES",
    "DDResolveDismissExceptionOutcome",
    "DDDismissExceptionSitePrimaryPrivateTeardown",
    "DDDismissExceptionSiteSecondaryPrivateTeardown",
    "DDDismissExceptionSitePrivateCleanupRelease",
    "DDDismissExceptionSiteSlotZeroBridgeOffPublish",
    "DDDismissExceptionSiteLaterSlotBridgeOffPublish",
    "DDDismissExceptionSiteResetHostingState",
    "outcome.shouldSkipRemainingPrivateTeardown = YES",
    "outcome.shouldContinueBridgeOffPhase = YES",
    "outcome.primaryControllerIvarWasAlreadyCleared = YES",
    "outcome.secondaryControllerIvarsWereAlreadyCleared = YES",
    "outcome.shouldContinueLaterSlotPublications = YES",
    "outcome.shouldContinueSlotLoop = YES",
    "outcome.exceptionWouldPropagate = YES",
    "DDResolveConvertSlotToCarPlayExceptionOutcome",
    "DDConvertSlotToCarPlayExceptionSitePrivateHostedViewTeardown",
    "DDConvertSlotToCarPlayExceptionSiteBridgeOffPublish",
    "outcome.shouldContinueControllerIvarClear = YES",
    "outcome.shouldContinueBridgeOffPhase = YES",
    "outcome.shouldCommitHostedBundleState = YES",
    "outcome.shouldSetCarPlayFlag = YES",
    "outcome.controllerIvarWasAlreadyClearedBeforeCatch = YES",
    "DDResolveSpikeHostSlotsLandscapeExceptionOutcome",
    "DDSpikeHostSlotsLandscapeExceptionSiteTypedBeforeAuxStateCommit",
    "DDSpikeHostSlotsLandscapeExceptionSiteTypedAfterAuxStateCommit",
    "DDSpikeHostSlotsLandscapeExceptionSiteActionZeroCleanup",
    "outcome.shouldClearParsedLandscapeOrientation = YES",
    "outcome.shouldResolveFallbackOrientation = YES",
    "outcome.shouldContinueHosting = YES",
    "outcome.swapStateWouldRemainCommitted = YES",
    "outcome.crossSwapStateWouldRemainCommitted = YES",
    "outcome.rotationStateWouldRemainCommitted = YES",
    "outcome.exceptionWouldPropagate = YES",
    "DDResolveAuxSceneTeardownExceptionOutcome",
    "DDAuxSceneTeardownExceptionSitePrivateViewTeardown",
    "DDAuxSceneTeardownExceptionSiteUnprotectedRange",
    "outcome.auxControllerIvarWasAlreadyClearedBeforeCatch = YES",
    "outcome.shouldSkipRemainingPrivateTeardown = YES",
    "outcome.shouldContinueAuxStateReset = YES",
    "outcome.shouldRefreshAuxGenerationState = YES",
    "outcome.retainedViewReleaseCouldBeBypassed = YES",
    "DDResolveAuxSceneCreationExceptionOutcome",
    "DDAuxSceneCreationExceptionSiteProtectedCreationWork",
    "DDAuxSceneCreationExceptionSiteProtectedFailureTeardown",
    "DDAuxSceneCreationExceptionSiteCatchTeardown",
    "DDAuxSceneCreationExceptionSiteUnprotectedRange",
    "outcome.shouldInvokeTeardownFromCatch = YES",
    "outcome.shouldRetryTeardownFromCatch = YES",
    "outcome.shouldSkipRemainingCreation = YES",
    "outcome.shouldReturnNilScene = YES",
    "outcome.shouldEndActiveCatchBeforeResumeUnwind = YES",
    "DDResolveDegradeSlotExceptionOutcome",
    "DDDegradeSlotExceptionSitePrivateControllerTeardown",
    "DDDegradeSlotExceptionSiteUnprotectedRange",
    "outcome.controllerIvarClearStillPendingAtCatch = YES",
    "outcome.shouldContinueControllerIvarClear = YES",
    "outcome.shouldContinueHostedBidReset = YES",
    "outcome.shouldContinuePlaceholderCreation = YES",
    "DDResolveSpikeCreateSlotExceptionOutcome",
    "DDSpikeCreateSlotExceptionSitePreControllerPrivateWork",
    "DDSpikeCreateSlotExceptionSitePostControllerPrivateWork",
    "DDSpikeCreateSlotExceptionSitePrivateDeviceDecoration",
    "DDSpikeCreateSlotExceptionSitePlaceholderCreationAfterApplicationMiss",
    "DDSpikeCreateSlotExceptionSiteFailureDegradeBeforeControllerStore",
    "DDSpikeCreateSlotExceptionSiteFailureDegradeAfterControllerStore",
    "DDSpikeCreateSlotExceptionSiteCatchDegrade",
    "DDSpikeCreateSlotExceptionSiteUnprotectedRange",
    "outcome.spikeInProgressFlagWasAlreadySet = YES",
    "outcome.hostedBidAndNativeStateWereCommittedBeforeProtectedRange = YES",
    "outcome.controllerIvarHadBeenStoredBeforeProtectedCall = YES",
    "outcome.shouldRouteThroughDegradeFromCatch = YES",
    "outcome.shouldRetryDegradeFromCatch = YES",
    "outcome.shouldSkipRemainingPrivateDecoration = YES",
    "outcome.shouldContinueReturningMainView = YES",
    "outcome.shouldReturnDegradedResult = YES",
    "DDResolveCNABBuildSceneHostExceptionOutcome",
    "DDCNABBuildSceneHostExceptionSitePreControllerPrivateWork",
    "DDCNABBuildSceneHostExceptionSitePostControllerPrivateWork",
    "DDCNABBuildSceneHostExceptionSitePrivateDeviceDecoration",
    "DDCNABBuildSceneHostExceptionSiteFailureReset",
    "DDCNABBuildSceneHostExceptionSiteCatchReset",
    "DDCNABBuildSceneHostExceptionSiteUnprotectedRange",
    "outcome.shouldInvokeResetHostingStateFromCatch = YES",
    "outcome.shouldRetryResetHostingStateFromCatch = YES",
    "outcome.shouldForceNilReturn = YES",
    "outcome.retainedIntermediateReleasesCouldBeBypassed = YES",
    "outcome.mainViewHadBeenAcquiredBeforeProtectedCall = YES",
    "outcome.shouldContinueReturningMainView = YES",
    "outcome.retainedDeviceControllerReleaseCouldBeBypassed = YES",
    "DDResolveEvictFromPhoneExceptionOutcome",
    "DDEvictFromPhoneExceptionSiteWorkspaceClassLookup",
    "DDEvictFromPhoneExceptionSiteWorkspacePreparation",
    "DDEvictFromPhoneExceptionSiteTransitionRequestCreation",
    "DDEvictFromPhoneExceptionSiteApplicationContextPreparation",
    "DDEvictFromPhoneExceptionSiteApplicationContextMutation",
    "DDEvictFromPhoneExceptionSiteProtectedFallbackInvocation",
    "DDEvictFromPhoneExceptionSiteCompletionSelectorProbe",
    "DDEvictFromPhoneExceptionSiteCompletionHandlerInstall",
    "DDEvictFromPhoneExceptionSiteExecuteTransitionOrFallback",
    "DDEvictFromPhoneExceptionSiteEarlyProbeOrBypassCleanup",
    "DDEvictFromPhoneExceptionSiteCatchFallback",
    "DDEvictFromPhoneExceptionSiteUnprotectedRange",
    "outcome.shouldInvokeFallbackWrapperFromCatch = YES",
    "outcome.shouldSkipRemainingEvictionWork = YES",
    "outcome.protectedFallbackThrowOccursAfterOneShotGateSet = YES",
    "outcome.catchFallbackMayBeSuppressedByOneShotGate = YES",
    "outcome.completionHandlerMayAlreadyBeInstalled = YES",
    "outcome.timeoutFallbackMayAlreadyBeScheduled = YES",
    "outcome.transitionExecutionMayHaveStarted = YES",
    "outcome.resumeUnwindRunsByrefCleanup = YES",
    "DDResolveSplitHostGeometryExceptionOutcome",
    "DDSplitHostGeometryExceptionSiteHostFrameSetter",
    "DDSplitHostGeometryExceptionSiteSplitCenterSetter",
    "DDSplitHostGeometryExceptionSiteGapRead",
    "DDSplitHostGeometryExceptionSiteFinalGeometrySync",
    "DDSplitHostGeometryExceptionSiteUnprotectedRange",
    "outcome.shouldSkipRemainingGeometryWork = YES",
    "outcome.shouldContinueRetainedViewCleanup = YES",
    "outcome.hostFrameCouldHaveAppliedBeforeException = YES",
    "outcome.hostFrameDefinitelyAppliedBeforeProtectedCall = YES",
    "outcome.splitCenterCouldHaveAppliedBeforeException = YES",
    "outcome.splitCenterDefinitelyAppliedBeforeProtectedCall = YES",
    "outcome.finalGeometrySyncCouldHaveStartedBeforeException = YES",
    "DDResolveSceneLayerHostPredicateExceptionOutcome",
    "DDSceneLayerHostPredicateExceptionSiteClassAndTraversalArraySetup",
    "DDSceneLayerHostPredicateExceptionSiteTraversalStep",
    "DDSceneLayerHostPredicateExceptionSiteTraversalCountRefresh",
    "DDSceneLayerHostPredicateExceptionSiteCandidateGeometryRead",
    "DDSceneLayerHostPredicateExceptionSiteUnprotectedRange",
    "outcome.shouldForcePredicateFalse = YES",
    "outcome.shouldAttemptPostScanCounterDecrement = YES",
    "outcome.shouldSkipRotationRebuildEvaluation = YES",
    "outcome.shouldContinueInputCleanup = YES",
    "outcome.retainedRootViewReleaseCouldBeBypassed = YES",
    "outcome.retainedTraversalArrayReleaseCouldBeBypassed = YES",
    "outcome.retainedCurrentCandidateReleaseCouldBeBypassed = YES",
    "outcome.retainedSubviewsReleaseCouldBeBypassed = YES",
    "outcome.candidateGeometryReadCouldHaveStartedBeforeException = YES",
    "DDResolveSlideAnimationExceptionOutcome",
    "DDSlideAnimationExceptionSiteUIViewAnimationCall",
    "DDSlideAnimationExceptionSiteCatchFallbackCenterSetter",
    "DDSlideAnimationExceptionSiteUnprotectedRange",
    "outcome.slideFlagWasAlreadySet = YES",
    "outcome.oneSecondFollowupWasAlreadyScheduled = YES",
    "outcome.targetCenterWasAlreadyComputed = YES",
    "outcome.animationCouldHaveStartedBeforeException = YES",
    "outcome.shouldInvokeDirectCenterFallback = YES",
    "outcome.retainedAnimationCaptureReleaseCouldBeBypassed = YES",
    "outcome.shouldContinuePrimaryViewAndInputCleanup = YES",
    "outcome.directCenterFallbackCouldHaveAppliedBeforeException = YES",
    "DDResolveRecursiveTransparencyExceptionOutcome",
    "DDRecursiveTransparencyExceptionSiteBackgroundColorSetup",
    "DDRecursiveTransparencyExceptionSiteOpaqueSetter",
    "DDRecursiveTransparencyExceptionSiteInitialSubviewsEnumeration",
    "DDRecursiveTransparencyExceptionSiteRecursiveChildStep",
    "DDRecursiveTransparencyExceptionSiteNextEnumerationBatch",
    "DDRecursiveTransparencyExceptionSiteCleanupUnwind",
    "DDRecursiveTransparencyExceptionSiteUnprotectedRange",
    "outcome.shouldAbortRemainingTraversal = YES",
    "outcome.backgroundColorCouldHaveAppliedBeforeException = YES",
    "outcome.backgroundColorDefinitelyAppliedBeforeProtectedCall = YES",
    "outcome.opaqueCouldHaveAppliedBeforeException = YES",
    "outcome.opaqueDefinitelyAppliedBeforeProtectedCall = YES",
    "outcome.retainedClearColorReleaseCouldBeBypassed = YES",
    "outcome.retainedSubviewsArrayReleaseCouldBeBypassed = YES",
    "outcome.recursiveChildExceptionCouldBeSwallowedByParent = YES",
    "outcome.recursiveChildMayHavePartiallyMutatedDescendantsBeforeException = YES",
    "outcome.priorEnumerationBatchDefinitelyCompletedBeforeProtectedCall = YES",
    "outcome.shouldResumeUnwindFromCleanup = YES",
    "DDResolveTopLevelTransparencyExceptionOutcome",
    "DDTopLevelTransparencyExceptionSiteHostBackgroundColor",
    "DDTopLevelTransparencyExceptionSiteHostOpaqueSetter",
    "DDTopLevelTransparencyExceptionSiteSplitBackgroundColor",
    "DDTopLevelTransparencyExceptionSiteSplitOpaqueSetter",
    "DDTopLevelTransparencyExceptionSiteRecursiveRoot",
    "DDTopLevelTransparencyExceptionSiteUnprotectedRange",
    "outcome.shouldReturnImmediately = YES",
    "outcome.hostBackgroundCouldHaveAppliedBeforeException = YES",
    "outcome.hostBackgroundDefinitelyAppliedBeforeProtectedCall = YES",
    "outcome.hostOpaqueCouldHaveAppliedBeforeException = YES",
    "outcome.hostOpaqueDefinitelyAppliedBeforeProtectedCall = YES",
    "outcome.splitBackgroundCouldHaveAppliedBeforeException = YES",
    "outcome.splitBackgroundDefinitelyAppliedBeforeProtectedCall = YES",
    "outcome.splitOpaqueCouldHaveAppliedBeforeException = YES",
    "outcome.splitOpaqueDefinitelyAppliedBeforeProtectedCall = YES",
    "outcome.recursiveRootExceptionCouldBeSwallowedByWrapper = YES",
    "outcome.recursiveRootMayHavePartiallyMutatedSubtreeBeforeException = YES",
    "DDResolveCNABKeyPaneHideSymbolExceptionOutcome",
    "DDCNABKeyPaneHideSymbolExceptionSiteSymbolConfiguration",
    "DDCNABKeyPaneHideSymbolExceptionSiteSymbolImageLookup",
    "DDCNABKeyPaneHideSymbolExceptionSiteSymbolImageViewInit",
    "DDCNABKeyPaneHideSymbolExceptionSiteManualFallbackUnprotected",
    "DDCNABKeyPaneHideSymbolExceptionSiteOtherUnprotectedRange",
    "outcome.shouldSkipRemainingSymbolPath = YES",
    "outcome.shouldContinueManualChevronFallback = YES",
    "outcome.symbolConfigurationDefinitelyRetainedBeforeProtectedCall = YES",
    "outcome.symbolImageDefinitelyRetainedBeforeProtectedCall = YES",
    "outcome.retainedSymbolConfigurationReleaseCouldBeBypassed = YES",
    "outcome.retainedSymbolImageReleaseCouldBeBypassed = YES",
    "DDResolveKeyPaneHideGapExceptionOutcome",
    "DDKeyPaneHideGapExceptionSiteFileRead",
    "DDKeyPaneHideGapExceptionSiteLengthRead",
    "DDKeyPaneHideGapExceptionSiteUTF8StringRead",
    "DDKeyPaneHideGapExceptionSiteNumericParse",
    "DDKeyPaneHideGapExceptionSiteRetainAutoreleaseGap",
    "DDKeyPaneHideGapExceptionSiteOtherUnprotectedRange",
    "outcome.shouldReturnDefaultGap = YES",
    "outcome.defaultGap = 71.0",
    "outcome.retainedStringDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.retainedStringReleaseCouldBeBypassed = YES",
    "outcome.retainAutoreleaseCouldHaveStartedBeforeException = YES",
    "DDResolveDisplayScaleCapExceptionOutcome",
    "DDDisplayScaleCapExceptionSiteDisplayAcquisition",
    "DDDisplayScaleCapExceptionSiteDisplayClassLookup",
    "DDDisplayScaleCapExceptionSiteConfigurationConstruction",
    "DDDisplayScaleCapExceptionSiteScaleCapabilityProbe",
    "DDDisplayScaleCapExceptionSiteScaleGetter",
    "DDDisplayScaleCapExceptionSiteWindowBoundsRead",
    "DDDisplayScaleCapExceptionSitePixelSizeCapabilityProbe",
    "DDDisplayScaleCapExceptionSitePixelSizeGetter",
    "DDDisplayScaleCapExceptionSiteUnprotectedRange",
    "outcome.shouldReturnOriginalBoundsDimension = YES",
    "outcome.shouldSkipDisplayScaleCap = YES",
    "outcome.retainedDisplayDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.retainedDisplayReleaseCouldBeBypassed = YES",
    "outcome.retainedConfigurationDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.retainedConfigurationReleaseCouldBeBypassed = YES",
    "outcome.temporaryConfigurationConstructionCouldHaveStartedBeforeException = YES",
    "outcome.temporaryConfigurationReleaseCouldBeBypassed = YES",
    "outcome.retainedWindowDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.retainedWindowReleaseCouldBeBypassed = YES",
    "DDResolvePropertyListWriterExceptionOutcome",
    "DDPropertyListWriterExceptionSiteSerialization",
    "DDPropertyListWriterExceptionSiteDataWrite",
    "DDPropertyListWriterExceptionSiteFileManagerAcquisition",
    "DDPropertyListWriterExceptionSitePermissionsDictionaryConstruction",
    "DDPropertyListWriterExceptionSiteSetAttributes",
    "DDPropertyListWriterExceptionSiteIntermediateCleanupUnwind",
    "DDPropertyListWriterExceptionSiteFinalArgumentCleanupUnwind",
    "DDPropertyListWriterExceptionSiteUnprotectedRange",
    "outcome.shouldReturnFalse = YES",
    "outcome.shouldReturnTrueAfterSuccessfulWrite = YES",
    "outcome.dataWriteDefinitelySucceededBeforeProtectedCall = YES",
    "outcome.retainedDataDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.retainedDataReleaseCouldBeBypassed = YES",
    "outcome.shouldContinueRetainedDataCleanup = YES",
    "outcome.temporaryFileManagerAcquisitionCouldHaveStartedBeforeException = YES",
    "outcome.temporaryFileManagerReleaseCouldBeBypassed = YES",
    "outcome.retainedFileManagerDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.retainedFileManagerReleaseCouldBeBypassed = YES",
    "outcome.temporaryPermissionsDictionaryConstructionCouldHaveStartedBeforeException = YES",
    "outcome.temporaryPermissionsDictionaryReleaseCouldBeBypassed = YES",
    "outcome.retainedPermissionsDictionaryDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.retainedPermissionsDictionaryReleaseCouldBeBypassed = YES",
    "outcome.fileAttributesCouldHaveAppliedBeforeException = YES",
    "DDResolveKeyPaneHostConstructionExceptionOutcome",
    "DDKeyPaneHostConstructionExceptionSiteOuterViewBackgroundSetup",
    "DDKeyPaneHostConstructionExceptionSiteOuterViewOpaqueSetter",
    "DDKeyPaneHostConstructionExceptionSiteInnerViewAndSceneEmbedding",
    "DDKeyPaneHostConstructionExceptionSiteInnerOpaqueAndHierarchyInsertion",
    "DDKeyPaneHostConstructionExceptionSiteHideGapRead",
    "DDKeyPaneHostConstructionExceptionSiteLeftHideKeyCreation",
    "DDKeyPaneHostConstructionExceptionSiteRightHideKeyCreationAndInsertion",
    "DDKeyPaneHostConstructionExceptionSiteGeometryAndStateCommit",
    "DDKeyPaneHostConstructionExceptionSiteTransparencyWrapper",
    "DDKeyPaneHostConstructionExceptionSiteFrontingAndActivation",
    "DDKeyPaneHostConstructionExceptionSiteUnprotectedRange",
    "outcome.shouldClearLeftKeyGlobal = YES",
    "outcome.shouldClearRightKeyGlobal = YES",
    "outcome.shouldInvokeAuxSceneTeardown = YES",
    "outcome.shouldClearOuterHostGlobal = YES",
    "outcome.innerViewGlobalNotExplicitlyClearedByCatch = YES",
    "outcome.auxSceneGlobalNotExplicitlyClearedByCatch = YES",
    "outcome.geometrySyncCouldHaveStartedBeforeException = YES",
    "outcome.sizeAndFlagsCouldBePartiallyCommittedBeforeException = YES",
    "outcome.geometrySizeAndFlagsDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.mediaTimeAndGenerationDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.initialDelayedDispatchesDefinitelyScheduledBeforeProtectedCall = YES",
    "outcome.transparencyCouldHaveStartedBeforeException = YES",
    "outcome.transparencyWrapperDefinitelyCompletedBeforeProtectedCall = YES",
    "outcome.fourStaggeredDispatchesDefinitelyScheduledBeforeProtectedCall = YES",
    "outcome.frontingCouldHaveAppliedBeforeException = YES",
    "outcome.activationCouldHaveStartedBeforeException = YES",
    "DDResolvePropertyListReaderExceptionOutcome",
    "DDPropertyListReaderExceptionSiteDataRead",
    "DDPropertyListReaderExceptionSitePropertyListDecode",
    "DDPropertyListReaderExceptionSiteDictionaryTypeCheck",
    "DDPropertyListReaderExceptionSiteUnprotectedRange",
    "outcome.shouldReturnNil = YES",
    "outcome.retainedDataDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.retainedDataReleaseCouldBeBypassed = YES",
    "outcome.propertyListDecodeCouldHaveStartedBeforeException = YES",
    "outcome.retainedPropertyListDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.retainedPropertyListReleaseCouldBeBypassed = YES",
    "DDResolveKeyboardLostRecoveryExceptionOutcome",
    "DDKeyboardLostRecoveryExceptionSiteSharedControllerAcquisition",
    "DDKeyboardLostRecoveryExceptionSiteSceneSummaryAcquisition",
    "DDKeyboardLostRecoveryExceptionSiteUnprotectedRange",
    "outcome.shouldUseFallbackSceneSummary = YES",
    "outcome.shouldContinueMarkerAndRebuildFlow = YES",
    "outcome.temporaryControllerAcquisitionCouldHaveStartedBeforeException = YES",
    "outcome.temporaryControllerReleaseCouldBeBypassed = YES",
    "outcome.retainedControllerDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.retainedControllerReleaseCouldBeBypassed = YES",
    "outcome.temporarySceneSummaryAcquisitionCouldHaveStartedBeforeException = YES",
    "outcome.temporarySceneSummaryReleaseCouldBeBypassed = YES",
    "DDResolveCarPlayUIStatusCallbackExceptionOutcome",
    "DDCarPlayUIStatusCallbackExceptionSiteSharedControllerAcquisition",
    "DDCarPlayUIStatusCallbackExceptionSiteStatusCallbackSend",
    "DDCarPlayUIStatusCallbackExceptionSiteUnprotectedRange",
    "outcome.shouldSwallowAnyException = YES",
    "outcome.shouldReturnImmediately = YES",
    "outcome.callbackCouldHaveAppliedSideEffectsBeforeException = YES",
    "DDResolveDropSplashIfOverdueExceptionOutcome",
    "DDDropSplashIfOverdueExceptionSiteSharedControllerAcquisition",
    "DDDropSplashIfOverdueExceptionSiteDropSelectorSend",
    "DDDropSplashIfOverdueExceptionSiteUnprotectedRange",
    "outcome.dropSelectorCouldHaveAppliedSideEffectsBeforeException = YES",
    "DDResolveDropServerNoticeNowExceptionOutcome",
    "DDDropServerNoticeNowExceptionSiteSharedControllerAcquisition",
    "DDDropServerNoticeNowExceptionSiteDropSelectorSend",
    "DDDropServerNoticeNowExceptionSiteUnprotectedRange",
    "DDResolveDropOverdueNoticeExceptionOutcome",
    "DDDropOverdueNoticeExceptionSiteSharedControllerAcquisition",
    "DDDropOverdueNoticeExceptionSiteDropSelectorSend",
    "DDDropOverdueNoticeExceptionSiteUnprotectedRange",
    "DDResolveNudgePresentGateExceptionOutcome",
    "DDNudgePresentGateExceptionSiteSharedControllerAcquisition",
    "DDNudgePresentGateExceptionSiteVisibleCheck",
    "DDNudgePresentGateExceptionSiteLivePresentRunningCheck",
    "DDNudgePresentGateExceptionSiteFileManagerAcquisition",
    "DDNudgePresentGateExceptionSiteMarkerFileCheck",
    "DDNudgePresentGateExceptionSiteNudgePresentSend",
    "DDNudgePresentGateExceptionSiteUnprotectedRange",
    "outcome.visibleCheckDefinitelyPassedBeforeProtectedCall = YES",
    "outcome.livePresentCheckDefinitelyReturnedFalseBeforeProtectedCall = YES",
    "outcome.temporaryFileManagerAcquisitionCouldHaveStartedBeforeException = YES",
    "outcome.temporaryFileManagerReleaseCouldBeBypassed = YES",
    "outcome.retainedFileManagerDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.retainedFileManagerReleaseCouldBeBypassed = YES",
    "outcome.markerCheckDefinitelyCompletedBeforeProtectedCall = YES",
    "outcome.markerDefinitelyAbsentBeforeProtectedCall = YES",
    "outcome.fileManagerReleaseDefinitelyCompletedBeforeProtectedCall = YES",
    "outcome.nudgeCouldHaveAppliedSideEffectsBeforeException = YES",
    "DDResolveDisplayBoundsFallbackExceptionOutcome",
    "DDDisplayBoundsFallbackExceptionSiteMainScreenAcquisition",
    "DDDisplayBoundsFallbackExceptionSiteBoundsRead",
    "DDDisplayBoundsFallbackExceptionSiteUnprotectedRange",
    "outcome.shouldReturnZero = YES",
    "outcome.shouldIgnoreBoundsResult = YES",
    "outcome.boundsDimensionsDefinitelyUncommittedBeforeCatch = YES",
    "outcome.temporaryScreenAcquisitionCouldHaveStartedBeforeException = YES",
    "outcome.temporaryScreenReleaseCouldBeBypassed = YES",
    "outcome.retainedScreenDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.retainedScreenReleaseCouldBeBypassed = YES",
    "DDResolveLayoutAreaPublishExceptionOutcome",
    "DDLayoutAreaPublishExceptionSiteInitialRectEmptyCheck",
    "DDLayoutAreaPublishExceptionSiteDockSuffixLabelAppend",
    "DDLayoutAreaPublishExceptionSiteStatusStringFormatting",
    "DDLayoutAreaPublishExceptionSiteStatusDedupEquality",
    "DDLayoutAreaPublishExceptionSiteGlobalStatusStoreUnwind",
    "DDLayoutAreaPublishExceptionSitePreferencesSetValue",
    "DDLayoutAreaPublishExceptionSitePreferencesSynchronize",
    "DDLayoutAreaPublishExceptionSiteDarwinCenterAcquisition",
    "DDLayoutAreaPublishExceptionSiteNotificationNameConstruction",
    "DDLayoutAreaPublishExceptionSiteDarwinNotificationPost",
    "DDLayoutAreaPublishExceptionSiteFinalStatusCleanupUnwind",
    "DDLayoutAreaPublishExceptionSiteFinalLabelCleanupUnwind",
    "DDLayoutAreaPublishExceptionSiteUnprotectedRange",
    "outcome.temporaryLabelConstructionCouldHaveStartedBeforeException = YES",
    "outcome.temporaryStatusStringConstructionCouldHaveStartedBeforeException = YES",
    "outcome.globalStatusCouldHaveAppliedBeforeException = YES",
    "outcome.globalStatusDefinitelyStoredBeforeProtectedCall = YES",
    "outcome.preferencesValueDefinitelySetBeforeProtectedCall = YES",
    "outcome.preferencesSynchronizeDefinitelyCompletedBeforeProtectedCall = YES",
    "outcome.darwinCenterDefinitelyAcquiredBeforeProtectedCall = YES",
    "outcome.notificationNameDefinitelyConstructedBeforeProtectedCall = YES",
    "outcome.notificationCouldHavePostedBeforeException = YES",
    "outcome.statusStringReleaseDefinitelyCompletedBeforeProtectedCall = YES",
    "outcome.shouldResumeUnwindFromActionZero = YES",
    "DDResolveDisplayConfigurationPublishExceptionOutcome",
    "DDDisplayConfigurationPublishExceptionSiteDisplayAcquisition",
    "DDDisplayConfigurationPublishExceptionSiteConfigurationClassLookup",
    "DDDisplayConfigurationPublishExceptionSiteConfigurationConstruction",
    "DDDisplayConfigurationPublishExceptionSitePixelSizeCapabilityCheck",
    "DDDisplayConfigurationPublishExceptionSitePixelSizeRead",
    "DDDisplayConfigurationPublishExceptionSiteScaleCapabilityCheck",
    "DDDisplayConfigurationPublishExceptionSiteScaleRead",
    "DDDisplayConfigurationPublishExceptionSiteBoundsCapabilityCheck",
    "DDDisplayConfigurationPublishExceptionSiteBoundsRead",
    "DDDisplayConfigurationPublishExceptionSiteFrameCapabilityCheck",
    "DDDisplayConfigurationPublishExceptionSiteFrameRead",
    "DDDisplayConfigurationPublishExceptionSiteResolutionStringFormatting",
    "DDDisplayConfigurationPublishExceptionSiteResolutionDedupEquality",
    "DDDisplayConfigurationPublishExceptionSiteQualityDedupEquality",
    "DDDisplayConfigurationPublishExceptionSiteResolutionPreferenceSet",
    "DDDisplayConfigurationPublishExceptionSiteQualityPreferenceSet",
    "DDDisplayConfigurationPublishExceptionSitePreferencesSynchronize",
    "DDDisplayConfigurationPublishExceptionSiteDarwinCenterAcquisition",
    "DDDisplayConfigurationPublishExceptionSiteNotificationNameConstruction",
    "DDDisplayConfigurationPublishExceptionSiteDarwinNotificationPost",
    "DDDisplayConfigurationPublishExceptionSiteUnprotectedRange",
    "outcome.shouldContinueAtDisplayBoundsFallback = YES",
    "outcome.shouldContinueAtGeometryValidityGate = YES",
    "outcome.shouldRestorePixelWidthFallbackBeforeContinuation = YES",
    "outcome.shouldKeepScaleAtZeroFallbackBeforeContinuation = YES",
    "outcome.shouldSkipScaleDerivationBeforeValidityGate = YES",
    "outcome.geometryGlobalsDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.resolutionGlobalDefinitelyStoredBeforeProtectedCall = YES",
    "outcome.qualityGlobalDefinitelyStoredBeforeProtectedCall = YES",
    "outcome.resolutionPreferenceCouldHaveAppliedBeforeException = YES",
    "outcome.qualityPreferenceCouldHaveAppliedBeforeException = YES",
    "outcome.notificationCouldHavePostedBeforeException = YES",
    "DDResolveKeyPaneCenterAdjustmentExceptionOutcome",
    "DDKeyPaneCenterAdjustmentExceptionSiteGeometryHelpers",
    "DDKeyPaneCenterAdjustmentExceptionSiteCenterGetter",
    "DDKeyPaneCenterAdjustmentExceptionSiteCenterSetter",
    "DDKeyPaneCenterAdjustmentExceptionSiteUnprotectedRange",
    "outcome.shouldSkipRemainingGeometryWork = YES",
    "outcome.shouldContinueFinalRetainedViewCleanup = YES",
    "outcome.preGeometryCallbackDefinitelyCompletedBeforeProtectedCall = YES",
    "outcome.retainedViewDefinitelyCommittedBeforeProtectedCall = YES",
    "outcome.retainedViewReleaseCouldBeBypassed = YES",
    "outcome.centerGetterDefinitelyCompletedBeforeProtectedCall = YES",
    "outcome.centerCouldHaveAppliedBeforeException = YES",
    "DDResolveKeyPaneRectangleForwardExceptionOutcome",
    "DDKeyPaneRectangleForwardExceptionSiteCandidateGeometryHelper",
    "DDKeyPaneRectangleForwardExceptionSiteCandidateNullCheck",
    "DDKeyPaneRectangleForwardExceptionSiteUnprotectedRange",
    "outcome.shouldForwardOriginalCallerRectangle = YES",
    "outcome.shouldSkipCandidateRectangleAdoption = YES",
    "outcome.shouldSkipGeometryCounterDecrement = YES",
    "outcome.shouldInvokeForwardCallback = YES",
    "outcome.shouldContinueFinalInputCleanup = YES",
    "outcome.candidateRectangleDefinitelyAcquiredBeforeProtectedCall = YES",
    "DDResolveKeyPaneCenterForwardExceptionOutcome",
    "DDKeyPaneCenterForwardExceptionSitePreGeometryHelper",
    "DDKeyPaneCenterForwardExceptionSiteCandidateGeometryHelper",
    "DDKeyPaneCenterForwardExceptionSiteCandidateNullCheck",
    "DDKeyPaneCenterForwardExceptionSiteCandidateMidX",
    "DDKeyPaneCenterForwardExceptionSiteCandidateMidY",
    "DDKeyPaneCenterForwardExceptionSiteUnprotectedRange",
    "outcome.shouldForwardOriginalCallerCenter = YES",
    "outcome.shouldSkipCandidateCenterAdoption = YES",
    "outcome.shouldSkipGeometryCounterDecrement = YES",
    "outcome.shouldInvokeCenterForwardCallback = YES",
    "outcome.candidateNullCheckDefinitelyCompletedBeforeProtectedCall = YES",
    "outcome.candidateMidXDefinitelyComputedBeforeProtectedCall = YES",
    "DDResolveStringSelectorExceptionOutcome",
    "DDStringSelectorExceptionOutcome outcome = { YES, YES, YES }",
    "DDResolveFrontmostPhoneIdentityExceptionOutcome",
    "DDFrontmostPhoneIdentityExceptionOutcome outcome = { YES, YES, YES }",
    "DDResolveActivatingEntitySetterExceptionOutcome",
    "DDActivatingEntitySetterExceptionOutcome outcome = { YES, YES }",
    "DDResolveHostUIAppRequestExceptionOutcome",
    "DDHostUIAppRequestExceptionOutcome outcome = { YES, YES, YES }",
    "DDResolveFBSUpdateIdentityRoute",
    "DDResolveAVCSceneHandleIdentityRoute",
    "DDResolveAVCSceneHandleUpdateDecision",
    "DDAVCSceneHandleUpdateHostSlot",
    "DDAVCSceneHandleUpdateAux",
    "decision.shouldAttemptGeneralCounterDecrement = YES",
    "decision.shouldReadSceneSettingsForAux = sceneSettingsSelectorSupported",
    "DDResolveAVCSceneHandleCallbackDecision",
    "decision.shouldCallOriginal = NO",
    "decision.shouldSuppressOriginal = YES",
    "if (suppressionCount <= 9)",
    "decision.nextSuppressionCount = suppressionCount + 1",
    "DDResolveHostSlotResizePrivateFollowup",
    "if (attemptCount >= 1)",
    "followup.nextAttemptCount = 0",
    "if (generalCounter <= 3)",
    "followup.nextGeneralCounter = 4",
    "followup.shouldProbePrivateScene = YES",
    "followup.shouldRequestPrivateSceneUpdate = YES",
    "followup.targetSize = DDApplyLandscapeSwapToSize(acceptedRawSize)",
    "DDResolveHostSlotResizePublishExceptionOutcome",
    "DDHostSlotResizePublishExceptionOutcome outcome = { YES, YES, YES }",
    "DDConfiguredHostSlotIndexForBundleIdentifier(bundleIdentifier, NO)",
    "DDConfiguredHostSlotIndexForBundleIdentifier(bundleIdentifier, YES)",
    "DDSceneSettingsSnapshot",
    "DDResolveIdentityNativeSize",
    "DDResolveIdentityAdjustedSize",
    "(gDDAuxOrientation == 3 || gDDAuxOrientation == 4) && size.width > size.height",
    "return DDApplyLandscapeSwapToSize(size)",
    "DDResolveIdentityRawSettingsOrientation",
    "DDShouldAttemptDirectInterfaceOrientationRepair",
    "DDSceneSettingsSnapshotsEquivalent",
    "fabs(before.frameSize.width - after.frameSize.width) <= 0.5",
    "before.orientation == after.orientation && before.foreground == after.foreground",
    "DDShouldClearAuxSceneSettingsDiff",
    "!gDDAuxNoApplyDiff",
    "DDSceneCallbackSizeRewrite",
    "DDResolveSceneCallbackSizeRewrite",
    "!(originalSize.width > 0.0 && originalSize.height > 0.0)",
    "!(replacement.width > 0.0 && replacement.height > 0.0)",
    "DDResolveFBSUpdateIdentityRoute(bundleIdentifier)",
    "DDApplyLandscapeSwapToSize(DDResolveIdentityNativeSize(bundleIdentifier))",
    "rewrite.substituted = YES",
    "DDResolveSceneCallbackSizeRewriteWithSuccessCounter",
    "rewrite.nextSuccessCounter = successCounter",
    "rewrite.substituted && successCounter >= 1",
    "rewrite.shouldAttemptSuccessCounterDecrement = YES",
    "rewrite.nextSuccessCounter = successCounter - 1",
    "DDResolveSceneCallbackExceptionOutcome",
    "DDSceneCallbackExceptionSiteRouteEligibility",
    "DDSceneCallbackExceptionSiteNativeSizeResolution",
    "DDSceneCallbackExceptionSiteOriginalCallback",
    "outcome.shouldSwallowException = YES",
    "outcome.shouldCallOriginalAfterCatch = YES",
    "if (diagnosticCount <= 9)",
    "outcome.shouldIncrementDiagnosticCount = YES",
    "outcome.nextDiagnosticCount = diagnosticCount + 1",
    "DDResolveSceneOrientationEqualityResult",
    "return DDResolveIdentityRawSettingsOrientation(bundleIdentifier) == requestedOrientation",
    "DDShouldForceMutableSceneForeground",
    "mutableSettingsClassAvailable",
    "settingsIsMutableApplicationSceneSettings",
    "foregroundSetterSupported",
    "DDSceneDestroyDecisionKind",
    "DDSceneDestroyDecisionAuxDestroyedNotice",
    "DDSceneDestroyDecisionClearHostSlot",
    "DDSceneDestroyDecisionDismissHost",
    "DDResolveSceneDestroyDecision",
    "primaryBundleIdentifier.length > 0",
    "if (!gDDHostMirrorSplit || selected.length == 0)",
    "if (matchCount == 1)",
    "DDToAppsYieldDecision none = { DDToAppsYieldDecisionNone, -1 }",
    "DDToAppsYieldDecisionYieldThenCallOriginal",
    "DDToAppsYieldDecisionSwallowOriginal",
    "DDResolveToAppsYieldDecision",
    "if (!gDDHostMirrorActive || yieldInProgress)",
    "DDConfiguredHostSlotIndexForBundleIdentifier(bundleIdentifier, NO)",
    "swallowOriginalCallback",
    "DDResolveToAppsYieldExceptionOutcome",
    "DDToAppsYieldExceptionSitePreYieldRouting",
    "DDToAppsYieldExceptionSiteDismissSideEffect",
    "DDToAppsYieldExceptionSiteDisconnectSideEffect",
    "DDToAppsYieldExceptionSiteHideSideEffect",
    "DDToAppsYieldExceptionSiteYieldLogSideEffect",
    "DDToAppsYieldExceptionSiteOriginalCallback",
    "DDToAppsYieldExceptionSiteCleanup",
    "DDToAppsYieldExceptionContinuationCallOriginal",
    "DDToAppsYieldExceptionContinuationContinueYieldSideEffects",
    "DDToAppsYieldExceptionContinuationContinueYieldCleanup",
    "DDToAppsYieldExceptionContinuationCleanupReturn",
    "DDToAppsYieldExceptionContinuationResumeUnwind",
    "outcome.yieldInProgressWouldRemainSet = YES",
    "DDResolveOtherSettingsFlagClearDecision",
    "DDOtherSettingsFlagClearDecision decision = { NO, 0, 6 }",
    "settingsObjectPresent && otherSettingsPresent && flagSetterSupported",
    "DDResolveOtherSettingsFlagClearExceptionOutcome",
    "DDOtherSettingsFlagClearExceptionOutcome outcome = { YES, YES, YES }",
    "DDResolveExceptionReasonProbeDecision",
    "if (currentProbeCount > 19)",
    "decision.nextProbeCount = currentProbeCount + 1",
    "decision.shouldReadReason = reasonSelectorSupported",
    "DDResolveSceneOrientationExceptionOutcome",
    "DDSceneOrientationExceptionSiteDecisionPath",
    "DDSceneOrientationExceptionSiteOriginalCallback",
    "outcome.shouldCallOriginalAfterCatch = YES",
    "outcome.shouldApplyReasonProbeDecision = YES",
    "outcome.probeExceptionWouldResumeUnwind = YES",
    "outcome.shouldForceFalseResultAfterProbe = YES",
    "outcome.reasonProbeDecision = DDResolveExceptionReasonProbeDecision",
    "DDResolveSceneForegroundExceptionOutcome",
    "DDSceneForegroundExceptionSiteOriginalCallback",
    "DDSceneForegroundExceptionSiteRouteEligibility",
    "DDSceneForegroundExceptionSiteMutableSettingsPath",
    "outcome.shouldContinueForegroundEvaluationAfterCatch = YES",
    "outcome.shouldSkipRemainingForegroundForcing = YES",
    "DDResolveSceneDestroyExceptionOutcome",
    "DDSceneDestroyExceptionSitePreOriginalRouting",
    "DDSceneDestroyExceptionSiteOriginalCallback",
    "DDSceneDestroyExceptionSitePostCallbackDestroyRouting",
    "outcome.shouldRestoreSavedIdentityAfterCatch = YES",
    "outcome.preservesPreparedDestroyRoutingState = YES",
    "outcome.shouldContinuePreparedDestroyRoutingAfterOriginal = destroyRoutingPrepared",
    "outcome.exceptionWouldResumeUnwind = YES",
    "DDResolveAVCSceneHandleExceptionOutcome",
    "DDAVCSceneHandleExceptionSiteInitialSceneLookup",
    "DDAVCSceneHandleExceptionSiteUpdateRouting",
    "DDAVCSceneHandleExceptionSiteSuppressionDecision",
    "DDAVCSceneHandleExceptionSiteOriginalCallback",
    "outcome.shouldContinueSuppressionEvaluationAfterCatch = scenePresent",
    "outcome.shouldCallOriginalAfterCatch = !scenePresent",
    "DDResolvePrivateIntegerIvarWritePlan",
    "DDPrivateIvarWriteWidthByte",
    "DDPrivateIvarWriteWidthWord",
    "DDPrivateIvarWriteWidthDWord",
    "DDPrivateIvarWriteWidthQWord",
    "plan.shouldRecordUnsupportedType = YES",
    "DDResolvePrivateObjectIvarAccessPlan",
    "typeEncodingFirstByte == '@'",
    "plan.shouldReadObject = YES",
    "DDBuildPrivateIvarDiagnosticKey",
    "className ?: @\"nil\"",
    "ivarName ?: @\"?\"",
    "DDShouldInsertPrivateIvarDiagnostic",
    "return !alreadyRecorded",
    "DDResolveSceneSettingsPrivateIvarPlan",
    "[frameTypeEncoding hasPrefix:@\"{CGRect=\"]",
    "[foregroundTypeEncoding isEqualToString:@\"c\"]",
    "[foregroundTypeEncoding isEqualToString:@\"B\"]",
    "DDPrivateSceneIvarActionRecordUnsupported",
    "plan.shouldAttemptFailureBudgetDecrement = !(frameHandled && foregroundHandled)",
    "DDResolveSceneSettingsPrivateIvarExceptionOutcome",
    "DDSceneSettingsPrivateIvarExceptionOutcome outcome = { YES, YES, YES, YES }",
    "DDResolveFBSUpdateExceptionOutcome",
    "DDFBSUpdateExceptionSitePreSettingsPreparation",
    "DDFBSUpdateExceptionSiteSceneSettingsPath",
    "DDFBSUpdateExceptionSiteMutableSettingsPath",
    "DDFBSUpdateExceptionSiteRoutingDecisionOrExecution",
    "DDFBSUpdateExceptionSiteOriginalCallback",
    "DDFBSUpdateExceptionContinuationContinueMutableSettings",
    "DDFBSUpdateExceptionContinuationContinuePostSettingsRouting",
    "DDFBSUpdateExceptionContinuationCallOriginal",
    "DDFBSUpdateExceptionContinuationCleanupReturn",
    "DDResolveFBSSettingsCallbackExceptionOutcome",
    "DDFBSSettingsCallbackExceptionSiteCustomPath",
    "DDFBSSettingsCallbackExceptionSiteOriginalCallback",
    "outcome.shouldCallOriginalAfterCatch = YES",
    "outcome.shouldContinueCleanupAfterProbe = YES",
    "DDResolveFBSPresentationUpdateExceptionOutcome",
    "DDFBSPresentationUpdateExceptionSiteOriginalCallback",
    "DDFBSPresentationUpdateExceptionSiteNoPresentationUpdateFileProbe",
    "DDFBSPresentationUpdateExceptionSiteUpdateFrameAndTransform",
    "outcome.shouldContinuePostOriginalEvaluationAfterProbe = YES",
    "outcome.exceptionWouldResumeUnwind = YES",
    "outcome.shouldContinueCleanupAfterCatch = YES",
    "DDResolveCurrentInterfaceOrientationExceptionOutcome",
    "DDCurrentInterfaceOrientationExceptionOutcome outcome = { YES, 0 }",
    "DDResolveCurrentInterfaceOrientation",
    "settingsObjectPresent && interfaceOrientationSelectorSupported",
    "DDResolveFBSSceneSettingsUpdateDecision",
    "if (targetSize.width <= 0.0)",
    "DDFBSSceneSettingsUpdateReasonSlotNotMarked",
    "frameSelectorSupported ? currentFrameWidth : 0.0",
    "fabs(effectiveCurrentFrameWidth - targetSize.width) > 0.5",
    "desiredOrientation != 0 && currentOrientation != 0",
    "DDFBSSceneSettingsUpdateReasonOrientationMismatch",
    "DDPrivateUpdateSettingsMethodSignatureSupported",
    "[methodTypeEncoding characterAtIndex:0] == 'v'",
    "[methodTypeEncoding containsString:@\"@?\"]",
    "DDPrivateVoidIntegerSetterSignatureSupported",
    "argumentCount == 3 && returnTypeFirstByte == 'v'",
    "((unsigned char)valueArgumentTypeFirstByte & 0xDFu) == 'Q'",
    "DDResolveFBSSceneSettingsExecutorDecision",
    "!(targetSize.width > 0.0 && targetSize.height > 0.0)",
    "DDFBSSceneSettingsExecutorAdmissionReentrant",
    "if (attemptCount >= 13)",
    "DDFBSSceneSettingsExecutorAdmissionCapabilityUnavailable",
    "DDFBSSceneSettingsExecutorAdmissionInvalidMethodSignature",
    "DDFBSSceneSettingsExecutorAdmissionDispatch",
    "decision.shouldIncrementAttemptCount = YES",
    "DDResolveFBSSceneSettingsMutationPlan",
    "plan.shouldSetFrame = frameSetterSupported",
    "currentOrientation == 0 || currentOrientation == desiredOrientation",
    "plan.shouldSetInterfaceOrientation = YES",
    "plan.previousOrientation = currentOrientation",
    "plan.shouldRecordOrientationChange = YES",
    "DDResolveFBSSceneSettingsMutationExceptionOutcome",
    "DDFBSSceneSettingsMutationExceptionSiteFramePath",
    "DDFBSSceneSettingsMutationExceptionSiteOrientationPath",
    "outcome.shouldContinueOrientationAfterCatch = YES",
    "outcome.shouldContinueCleanupAfterCatch = YES",
    "outcome.nonmatchingCatchTypeWouldResumeUnwind = YES",
    "DDResolveFBSSceneSettingsExecutionAdmission",
    "if (capturedGeneration != currentGeneration)",
    "DDFBSSceneSettingsExecutionAdmissionReentrant",
    "admission.shouldEnterReentrantState = YES",
    "DDResolveFBSSceneSettingsInvocationOutcome",
    "DDFBSSceneSettingsInvocationCounterException",
    "outcome.shouldMarkSlot = ((NSUInteger)slotIndex <= 2)",
    "DDFBSSceneSettingsInvocationCounterOrientationChanged",
    "DDFBSSceneSettingsInvocationCounterGeneral",
    "outcome.shouldAttemptCounterDecrement = YES",
    "outcome.shouldClearReentrantState",
    "DDResolveFBSSceneSettingsExecutorExceptionOutcome",
    "DDFBSSceneSettingsExecutorExceptionSiteOuterBeforeAttemptIncrement",
    "DDFBSSceneSettingsExecutorExceptionSiteOuterAfterAttemptIncrement",
    "DDFBSSceneSettingsExecutorExceptionSitePrivateInvocation",
    "outcome.attemptCountWouldRemainIncremented = YES",
    "outcome.shouldDecrementExceptionCounter = currentExceptionCounter > 0",
    "outcome.shouldDisposeInvocationCaptures = YES",
    "outcome.nonmatchingCatchTypeWouldResumeUnwind = YES",
    "outcome.nonmatchingCatchTypeWouldClearReentrantState = NO",
    "settingsAttemptCount",
    "settingsBudget",
    "settingsExecutorReentrant",
    "duodash_kp_auxnoswap",
    "duodash_kp_noauxsid",
    "duodash_kp_noapplydiff",
    "gDDAuxGeneration++",
    "DDResolvePaneSettingsOrientation",
    "duodash_ab_nopaneorient",
    "gDDGeometryStateGeneration == gDDHostMirrorGeneration",
    "gDDPaneOrientationDisabled || gDDHostLandscapeOverrideOrientation != 0",
    "candidate >= 1 && candidate <= 4",
    "DDUpdateHostSlotRenderSize",
    "gDDHostMirrorSizes[slotIndex] = size",
    "DDPostUIAppState(bundleIdentifier, YES, gDDHostMirrorOrientation, YES",
    "DDSetHostSlotCarPlayUI",
    "DDConvertHostSlotToCarPlayUI",
    "DDDismissHostMirror",
    "index == 0 ? NO : YES",
    "dispatch_async(dispatch_get_main_queue(), dismissBlock)",
    "[NSThread isMainThread]",
    "DDPostUIAppState(bundleIdentifier, NO, gDDHostMirrorOrientation, YES, 0.0, 0.0)",
    "DDScheduleAppSideHandshake",
    "DDScheduleGeometryPushesForSlot",
    "DDReconstructionHostUIAppResponder",
    "DDConsumeHostUIAppRequestUserInfo",
    "DDStartSpringBoardUIAppResponder",
    "kDDHostRetryDelays[] = { 0.0, 0.4, 0.9, 1.8, 3.5 }",
    "gDDHostMirrorGeneration != capturedGeneration",
    "gDDHostMirrorCarPlayUI[slotIndex]",
    "size.width < 1.0 || size.height < 1.0",
    "DDPostUIAppState(bundleIdentifier, YES, capturedOrientation, YES",
    "DDRefreshCachedBridgeUISettings",
    "DDHostedNonCarPlayBundleIdentifiers",
    "DDSharedDDz2",
    "hostedSlotBids",
    "hostedSlotIsCarPlayUI",
    "hostedBundleId2",
    "com.sensetechlab.appbridge.uiapp.state",
    "com.sensetechlab.appbridge.uiapp.fontfloor",
    "com.sensetechlab.appbridge.uiapp.keypane",
    "DDAppendHostFrameMetrics",
    "DDPostHostRequest",
    "DDPostSplitHostRequest",
    "DDPostCarPlayUIStatus",
    "sizeof(DDHostFrameMetrics) == 104",
    "com.sensetechlab.appbridge.uiapp.request",
    "com.sensetechlab.appbridge.host.request",
    "com.sensetechlab.appbridge.host.request.split",
    "com.sensetechlab.appbridge.cpui.status",
    "frameWinValid",
    "cpWinW",
    "cpWinH",
    "bundleIdL",
    "bundleIdR",
    "bundleIdC",
    "skipEvict",
    "envOnly",
    "cpuiWhy",
    "DDPostHostRefusedState",
    "DDPostHostState",
    "NSDistributedNotificationCenter",
    "postNotificationName:object:userInfo:deliverImmediately:",
    "addObserver:selector:name:object:",
    "com.sensetechlab.appbridge.host.state",
    "cpuiKilled",
    "proc_pidpath",
    "com.apple.springboard",
    "UINT32_MAX",
    "strcmp(buffer, expectedPath) == 0",
    "DDReconstructionStart",
    "appbridge_split_enabled",
    "com.sensetechlab.appbridge.resolved",
    "DD_N_AUTOSTART_CHANGED",
    "CFNotificationSuspensionBehaviorDeliverImmediately",
    "CFBooleanGetTypeID",
    "return enabled || !valid",
    "value >= 8 && value <= 96",
    "duodash_ab_fontfloor_force",
]:
    if contract not in runtime:
        raise SystemExit(f"runtime contract missing: {contract}")

shared = (RECON / "DuoDashShared.h").read_text(encoding="utf-8")
if 'DD_N_AUTOSTART_CHANGED @"com.sensetechlab.autostart.changed"' not in shared:
    raise SystemExit("autostart Darwin notification constant drifted from decompile")
if 'DD_N_FONTFLOOR_CHANGED @"com.sensetechlab.fontfloor.changed"' not in shared:
    raise SystemExit("font-floor Darwin notification constant drifted from decompile")
if 'DD_N_KEYPANE_CHANGED @"com.sensetechlab.keypane.changed"' not in shared:
    raise SystemExit("keypane Darwin notification constant drifted from decompile")

print(
    f"OK: {len(REQUIRED_SYNTHESIS)} synthesis modules present; "
    "build scaffold and Substrate filter verified"
)
